config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index", as: "home"
  resources :order_items do
    resources :orders
  end
  resources :products
  resource :cart, only: [:show]
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :orders
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :update_total

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :authenticate_user!

  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.save
    session[:order_id] = @order.id
    redirect_to products_path
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    redirect_to cart_path
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if (@product.save)
      redirect_to home_path
    else
      render "new"
    end
  end

  private def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<% if @order_items.any? %>
  <p>
    Your total: <%= number_to_currency current_order.total_price %>
  </p>
  <p>
    Your balance: <%= number_to_currency (current_order.wallet - current_order.total_price)%>
  </p>
  <% @order_items.each do |item| %>
    <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), 
    :data => {:confirm => "You sure?", :method => "delete"} %></p>
    <p> 
      Unit price: <%= number_to_currency item.product.price %> <br> 
      Quantity: <%= item.quantity %> <br> 
      Total price: <%= number_to_currency (item.product.price * item.quantity) %>
    </p>
  <% end %>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>N456</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in?%>
      <ul class="nav">
        <li class="nav-item">
          <%= link_to 'New', new_product_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Home', home_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Order list', cart_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete , :class => 'nav-link' %>
        </li>
      </ul>
    <% else %>
    <ul class="nav">
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, :class => 'nav-link' %>
        </li>
      </ul>
    <%end%>
  
  
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="form-group">
    <h4>Product name:</h4>
     <%= f.text_field(:name) %>
  </div>
  <div class="form-group">
    <h4>Price:</h4>
     <%= f.number_field(:price) %>
     <%= f.submit ({:value => 'Save', :class => 'btn btn-success'})%>
  </div>
<%end%>

app/views/products/index.html.erb
 <% @products.each do |product| %>
  <%= form_for(@order_item) do |f| %>
    <%= product.name %><br><%= number_to_currency product.price %><br>
    <%= f.hidden_field :product_id, value: product.id %>
    <%= f.number_field :quantity %>
    <%= f.submit "Add to cart" %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<%= render 'form' %>